[package]
name = "monostyle_lexer"
version = "0.2.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Profile-driven tokenizer that extracts layout and complexity signals from source code."

[dependencies]
monostyle_core = { workspace = true }
monostyle_languages = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
