[package]
name = "monostyle"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Measure the complexity and readability of a codebase, a file, or a function."

[lib]
name = "monostyle"
path = "src/lib.rs"

[[bin]]
name = "monostyle"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
ignore = { workspace = true }
monostyle_core = { workspace = true }
monostyle_languages = { workspace = true }
monostyle_lexer = { workspace = true }
monostyle_markdown = { workspace = true }
monostyle_metrics = { workspace = true }
monostyle_rules = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
