[package]
name = "monostyle_markdown"
version = "0.3.3"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Extracts and analyzes the code fences and prose structure of Markdown documents."

[dependencies]
monostyle_core = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
