[package]
name = "monostyle_languages"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Language profiles that drive the monostyle lexer."

[dependencies]
monostyle_core = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
