//! Comment classification.
//!
//! Distinguishing a comment that explains *why* from one that restates *what* is the
//! single hardest heuristic in monostyle. It is a heuristic, so it is deliberately
//! conservative: it stays quiet when unsure, because wrongly penalizing a good comment
//! costs more reader trust than missing a bad one.

/// What a comment appears to be doing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CommentIntent {
	/// Explains reasoning, tradeoffs, constraints, or history. Rewarded.
	Why,
	/// Restates what the adjacent code plainly does. Penalized.
	How,
	/// A doc comment on a public item, which is expected rather than suspicious.
	Documentation,
	/// Machine directives: linters, formatters, license headers, TODOs.
	Directive,
	/// Too short or too ambiguous to classify.
	Neutral,
}

/// Markers that indicate a comment is explaining reasoning rather than restating code.
///
/// Each entry earns its place by being a phrase that is essentially never used to
/// narrate *what* code does — a comment saying "because" is always reaching for a
/// reason.
const WHY_MARKERS: &[&str] = &[
	"because",
	"so that",
	"otherwise",
	"to prevent",
	"to avoid",
	"workaround",
	"work around",
	"tradeoff",
	"trade-off",
	"intentionally",
	"deliberately",
	"on purpose",
	"must be",
	"has to be",
	"needs to be",
	"cannot be",
	"can't be",
	"would break",
	"breaking change",
	"for historical",
	"legacy",
	"backward compat",
	"backwards compat",
	"regression",
	"quirk",
	"caveat",
	"gotcha",
	"by design",
	"by convention",
	"invariant",
	"assumes",
	"precondition",
	"postcondition",
	"guarantees",
	"security:",
	"performance:",
	"perf:",
	"safety:",
	"note:",
	"why:",
	"hack",
	"fragile",
	"brittle",
	"race",
	"deadlock",
	"overflow",
	"precision",
	"rounding",
	"timezone",
	"deprecated",
	"temporary",
	"until",
	"we used to",
	"previously",
];

/// Markers that indicate a comment is narrating what the code does.
const HOW_MARKERS: &[&str] = &[
	"increment",
	"decrement",
	"set the",
	"sets the",
	"get the",
	"gets the",
	"call the",
	"calls the",
	"loop over",
	"loops over",
	"iterate over",
	"iterates over",
	"assign",
	"assigns",
	"initialize",
	"initializes",
	"return the",
	"returns the",
	"check if",
	"checks if",
	"create a",
	"creates a",
	"declare",
	"declares",
	"define the",
	"defines the",
	"add the",
	"adds the",
	"remove the",
	"removes the",
	"the following",
	"first,",
	"second,",
	"third,",
	"step 1",
	"step 2",
	"step one",
	"step two",
];

/// Prefixes that mark machine-readable directives rather than human prose.
const DIRECTIVE_PREFIXES: &[&str] = &[
	"todo",
	"fixme",
	"hack:",
	"note to",
	"xxx",
	"noqa",
	"nolint",
	"eslint",
	"clippy",
	"rustfmt",
	"dart ignore",
	"ignore:",
	"pragma",
	"region",
	"endregion",
	"markdownlint",
	"dprint",
	"copyright",
	"license",
	"spdx",
	"@ts-",
	"coverage",
	"istanbul",
	"generated",
	"do not edit",
	"autogenerated",
	"auto-generated",
];

/// Documentation comment markers, which are expected and neither rewarded nor penalized.
const DOCUMENTATION_PREFIXES: &[&str] =
	&["///", "//!", "//", "///<", "##", "<!--", "'''", "\"\"\""];

/// Classifies the body of a comment.
///
/// `is_doc_style` should be true when the comment uses the language's documentation
/// syntax, which changes the classification to [`CommentIntent::Documentation`].
#[must_use]
pub fn classify(body: &str, is_doc_style: bool) -> CommentIntent {
	let normalized = normalize(body);

	if normalized.is_empty() {
		return CommentIntent::Neutral;
	}

	if is_doc_style {
		return CommentIntent::Documentation;
	}

	if DIRECTIVE_PREFIXES
		.iter()
		.any(|prefix| normalized.starts_with(prefix))
	{
		return CommentIntent::Directive;
	}

	// A comment that has a URL, a ticket reference, or an issue link is pointing at
	// external context, which is exactly the kind of reason code cannot express itself.
	if contains_reference(&normalized) {
		return CommentIntent::Why;
	}

	let why_hits = WHY_MARKERS
		.iter()
		.filter(|marker| normalized.contains(*marker))
		.count();
	let how_hits = HOW_MARKERS
		.iter()
		.filter(|marker| normalized.contains(*marker))
		.count();

	if why_hits > 0 && why_hits >= how_hits {
		return CommentIntent::Why;
	}

	if how_hits > 0 {
		return CommentIntent::How;
	}

	// A long comment with no narration markers is more likely to be reasoning than
	// restating; a very short one is too ambiguous to call either way.
	if normalized.split_whitespace().count() >= 12 {
		return CommentIntent::Why;
	}

	CommentIntent::Neutral
}

/// Returns true when the comment begins with documentation syntax.
#[must_use]
pub fn is_doc_style(raw: &str) -> bool {
	let trimmed = raw.trim_start();

	DOCUMENTATION_PREFIXES.iter().any(|prefix| {
		trimmed.starts_with(prefix) && prefix.starts_with("//") || trimmed.starts_with("///")
	}) || trimmed.starts_with("///")
		|| trimmed.starts_with("//!")
		|| trimmed.starts_with("##")
}

/// Lowercases and collapses whitespace so marker matching is punctuation-insensitive.
fn normalize(body: &str) -> String {
	body.chars()
		.map(|character| {
			if character.is_ascii_punctuation() && character != ':' {
				' '
			} else {
				character
			}
		})
		.collect::<String>()
		.split_whitespace()
		.collect::<Vec<_>>()
		.join(" ")
		.to_lowercase()
}

/// Detects references to issues, docs, or specifications.
fn contains_reference(normalized: &str) -> bool {
	normalized.contains("http://")
		|| normalized.contains("https://")
		|| normalized.contains("see #")
		|| normalized.contains("issue #")
		|| normalized.contains("pr #")
		|| normalized.contains("rfc")
		|| normalized.contains("spec")
		|| normalized.contains("docs")
}
