//! Comment classification.
//!
//! Distinguishing a comment that explains *why* from one that restates *what* is the hardest
//! heuristic in monostyle, and the honest framing is that this is **a keyword matcher, not
//! comprehension**. It counts phrases from two curated lists and reports whichever list wins.
//! It has no model of the code being commented on and no understanding of the prose.
//!
//! Because it is a heuristic, three rules keep it from doing harm:
//!
//! 1. **Whole blocks are classified, not lines.** Reasoning usually sits on the first line of a
//!    multi-line comment and the continuation carries none of the markers. Judging lines
//!    independently credited the opening and penalized the rest, which made the verdict a
//!    function of where the author wrapped their text.
//! 2. **Documentation is never judged at all.** A doc comment is expected, not suspicious, so
//!    it short-circuits before any keyword matching runs.
//! 3. **No verdict is invented from length.** An earlier version credited any 12-word comment
//!    with no markers, which meant pure filler scored as reasoning. Ambiguity now reports
//!    [`CommentIntent::Neutral`]: silence is more honest than a guess.
//!
//! The known limitation is that substring matching cannot see negation or grammatical role, so
//! "Do not increment the counter" reads as narration. The lists are curated to keep that class of
//! error rare, and [`CommentIntent::Neutral`] absorbs the ambiguous middle.

/// What a comment appears to be doing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CommentIntent {
	/// Explains reasoning, tradeoffs, constraints, or history. Rewarded.
	Why,
	/// Restates what the adjacent code plainly does. Penalized.
	How,
	/// A doc comment on a public item, which is expected rather than suspicious.
	Documentation,
	/// Machine directives: linters, formatters, license headers, TODOs.
	Directive,
	/// Too short or too ambiguous to classify.
	Neutral,
}

/// Markers that indicate a comment is explaining reasoning rather than restating code.
///
/// Each entry earns its place by being a phrase that is essentially never used to narrate *what*
/// code does — a comment saying "because" is always reaching for a reason.
const WHY_MARKERS: &[&str] = &[
	"because",
	"so that",
	"otherwise",
	"to prevent",
	"to avoid",
	"workaround",
	"work around",
	"tradeoff",
	"trade-off",
	"intentionally",
	"deliberately",
	"on purpose",
	"must be",
	"has to be",
	"needs to be",
	"cannot be",
	"can't be",
	"would break",
	"breaking change",
	"for historical",
	"backward compat",
	"backwards compat",
	"regression",
	"quirk",
	"caveat",
	"gotcha",
	"by design",
	"by convention",
	"invariant",
	"assumes",
	"precondition",
	"postcondition",
	"guarantees",
	"security:",
	"performance:",
	"perf:",
	"safety:",
	"note:",
	"why:",
	"hack",
	"fragile",
	"brittle",
	"race",
	"deadlock",
	"overflow",
	"precision",
	"rounding",
	"timezone",
	"deprecated",
	"temporary",
	"until",
	"we used to",
	"previously",
	"not safe",
	"does not work",
	"doesn't work",
	"fails when",
	"breaks when",
	"only works",
	"required by",
	"relies on",
	"depends on",
	"in case",
	"even though",
	"so we",
	"so the",
	"so a",
	"so it",
];

/// Markers that indicate a comment is narrating what the code does.
///
/// These are deliberately narrow. A phrase like "declare" appears in ordinary explanatory prose
/// ("the literal was declared with single quotes"), so the entries here are limited to forms that
/// usually introduce a restatement of the adjacent line.
const HOW_MARKERS: &[&str] = &[
	"increment the",
	"decrement the",
	"set the value",
	"sets the value",
	"get the value",
	"gets the value",
	"call the function",
	"calls the function",
	"loop over the",
	"loops over the",
	"iterate over the",
	"iterates over the",
	"initialize the",
	"initializes the",
	"return the result",
	"returns the result",
	"check if the",
	"checks if the",
	"create a new",
	"creates a new",
	"declare a",
	"declares a",
	"define the function",
	"defines the function",
	"add the",
	"adds the",
	"remove the",
	"removes the",
	"step 1",
	"step 2",
	"step one",
	"step two",
	"first, we",
	"second, we",
	"third, we",
];

/// Prefixes that mark machine-readable directives rather than human prose.
const DIRECTIVE_PREFIXES: &[&str] = &[
	"todo",
	"fixme",
	"hack:",
	"note to",
	"xxx",
	"noqa",
	"nolint",
	"eslint",
	"clippy",
	"rustfmt",
	"dart ignore",
	"ignore:",
	"pragma",
	"region",
	"endregion",
	"markdownlint",
	"dprint",
	"copyright",
	"license",
	"spdx",
	"@ts-",
	"coverage",
	"istanbul",
	"generated",
	"do not edit",
	"autogenerated",
	"auto-generated",
];

/// Classifies a whole comment block.
///
/// Passing the entire block rather than one line is what keeps the verdict stable: the reasoning
/// in a comment's opening line is still visible when a marker on a later line is weighed against
/// it.
///
/// `is_doc_style` should be true when the block uses the language's documentation syntax. It
/// short-circuits to [`CommentIntent::Documentation`], because a documented public API is
/// expected rather than suspicious and should never be keyword-judged.
///
/// The remaining branches walk intent from most to least certain, because a comment can carry
/// several markers at once and the first decisive one is the verdict: a TODO inside reasoning is
/// still reasoning someone left behind.
#[must_use]
pub fn classify(block: &str, is_doc_style: bool) -> CommentIntent {
	if is_doc_style {
		return CommentIntent::Documentation;
	}

	let normalized = normalize(block);

	if normalized.is_empty() {
		return CommentIntent::Neutral;
	}

	if DIRECTIVE_PREFIXES
		.iter()
		.any(|prefix| normalized.starts_with(prefix))
	{
		return CommentIntent::Directive;
	}

	// A comment that has a URL, a ticket reference, or an issue link is pointing at external
	// context, which is exactly the kind of reason code cannot express itself.
	if contains_reference(&normalized) {
		return CommentIntent::Why;
	}

	let why_hits = WHY_MARKERS
		.iter()
		.filter(|marker| normalized.contains(*marker))
		.count();
	let how_hits = HOW_MARKERS
		.iter()
		.filter(|marker| normalized.contains(*marker))
		.count();

	match why_hits.cmp(&how_hits) {
		std::cmp::Ordering::Greater => CommentIntent::Why,
		std::cmp::Ordering::Less => CommentIntent::How,
		// A tie means the block contains both kinds of phrase, which is genuine ambiguity rather
		// than evidence for either verdict.
		std::cmp::Ordering::Equal => CommentIntent::Neutral,
	}
}

/// Lowercases and collapses whitespace so marker matching is punctuation-insensitive.
///
/// Colons survive normalization because several markers end in one (`security:`, `why:`), and
/// they are a reliable signal that a comment is labelling its reason.
fn normalize(body: &str) -> String {
	body.chars()
		.map(|character| {
			if character.is_ascii_punctuation() && character != ':' {
				' '
			} else {
				character
			}
		})
		.collect::<String>()
		.split_whitespace()
		.collect::<Vec<_>>()
		.join(" ")
		.to_lowercase()
}

/// Detects references to issues, docs, or specifications.
fn contains_reference(normalized: &str) -> bool {
	normalized.contains("http://")
		|| normalized.contains("https://")
		|| normalized.contains("see #")
		|| normalized.contains("issue #")
		|| normalized.contains("pr #")
		|| normalized.contains(" rfc")
		|| normalized.contains("spec ")
		|| normalized.contains("docs ")
}
